#!/bin/sh

# Depends on: 
#	- sdcv
#	- xclip (for selection support)
# 	- lynx (for html support)
# invocation: dictpopup [html] [word]
# - If no argument provided, the selection is used
# - If supplied with the html option, the dictionary output will be piped through lynx
#   in order to format html as plain text

if [ "$1" = "html"  ]; then
      word=${2:-$(xclip -o 2>/dev/null)}
      sdcv -n --utf8-output -e "$word" | format_output | 
	lynx -dump -stdin -assume_charset=UTF-8 -display_charset=UTF-8 | 
	xargs -0 popup
else
      word=${1:-$(xclip -o 2>/dev/null)}
      sdcv -n --utf8-output -e "$word" | format_output | xargs -0 popup
fi
